### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by gertjanspriensma**
I would use collector-url or something like that, by using /collector it looks like you have to append the localhost:5000 with /collector.

### CODE REVIEW

**Comment by ivarpruijn** [comment]
Thanks @gertjanspriensma! LGTM

**Review by sdirosa — APPROVED** [review]
Looks good. 

For context. This example was based on a CRA setup where we used its proxy option to map /collector to the actual collector BE via .env.

This allows for a single artifact build that can be used either for dev, staging or prod without needing to rebuild.

**Comment by ivarpruijn** [comment]
This is live now, thanks @gertjanspriensma : https://objectiv.io/docs/tracking/react/how-to-guides/getting-started

**Comment by sdirosa** [comment]
Follow up on this: https://github.com/objectiv/objectiv.io/pull/286

The confusing `endpoint` prop was all over the place. I have replaced it with an actual consistent URL everywhere. I think this should rule out pretty clearly what it actually is. 

I plan to explain properties one by one in a future documentation update. Including examples.

**Pull request merged**
