### PR TITLE
Different icon for homepage link

### PR DESCRIPTION
**Pull request by ivarpruijn**
Should also work on Mac now. 

- [x] @vincenthoogsteder Could you please check on your machine?
- [x] @jansenbob Do you like this icon?

### CODE REVIEW

**Comment by jansenbob** [comment]
@vincenthoogsteder i'm op a pc. could you post a screenshot?

**Comment by vincenthoogsteder** [comment]
Looks good
Screenshot 2021-12-01 at 11 42 07

**Comment by ivarpruijn** [comment]
Happy @jansenbob ?

**Comment by jansenbob** [comment]
I'm not super stoked, but I would say it's good enough for now. It's a low prio thing on my list to fix how the website link looks anyway, so let's ship it.

**Pull request merged**
